version: '3.7'

services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - mongo
    environment:
      - PORT=4000
      - MONGO_DB=mongodb://mongo:27017/autochat

volumes:
  mongo_data: